trigger:
- main

pool: Sage

steps:

- script: |
    ./mvnw package
  displayName: 'Build JAR'

- script: docker build -t kylerjacobson.dev .
  displayName: 'Build Docker Image'

- script: |
    docker login kyler.azurecr.io -u $(acr-user) -p $(acr-pass)
    docker tag kylerjacobson.dev kyler.azurecr.io/kylerjacobson.dev
    docker push kyler.azurecr.io/kylerjacobson.dev:latest