version: "3.8"

services:
    react-frontend:
        container_name: react-frontend
        build:
            context: .
        ports:
            - 8080:3000
        volumes:
            - ./src:/app/src
            - /app/node_modules
