version: "3"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: blog:v1.0.204
        ports:
            - "8080:8080"
        env_file:
            - ./server/.env
