# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - kylersdevblog

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://kyler.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_dcb3d1c32c1e41ddbbeae45281c50738 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9ee24af51a4a445da743ab0ca225a50b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: kyler.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_dcb3d1c32c1e41ddbbeae45281c50738 }}/blog-react-frontend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'kylersdevblog'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e45cdfede61f4443a7d40a4a0729571e }}
        images: 'kyler.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_dcb3d1c32c1e41ddbbeae45281c50738 }}/blog-react-frontend:${{ github.sha }}'